dist: xenial
before_install:
  - curl https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y google-chrome-unstable
env:
  - BROWSER_PATH=/usr/bin/google-chrome-unstable
gemfile:
  - gemfiles/capybara-2.x.gemfile
  - gemfiles/capybara-3.x.gemfile
  - gemfiles/websocket-driver-6.x.gemfile
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
matrix:
  exclude:
  - rvm: 2.3
    gemfile: gemfiles/websocket-driver-6.x.gemfile
  - rvm: 2.4
    gemfile: gemfiles/websocket-driver-6.x.gemfile
  - rvm: 2.6
    gemfile: gemfiles/websocket-driver-6.x.gemfile
